/**
 * generated by Xtext 2.25.0
 */
package fr.ensma.gimpleDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assign Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ensma.gimpleDsl.AssignOperation#getName <em>Name</em>}</li>
 *   <li>{@link fr.ensma.gimpleDsl.AssignOperation#isCast <em>Cast</em>}</li>
 *   <li>{@link fr.ensma.gimpleDsl.AssignOperation#getVcall <em>Vcall</em>}</li>
 *   <li>{@link fr.ensma.gimpleDsl.AssignOperation#getTempVariable <em>Temp Variable</em>}</li>
 *   <li>{@link fr.ensma.gimpleDsl.AssignOperation#getFunctionCall <em>Function Call</em>}</li>
 *   <li>{@link fr.ensma.gimpleDsl.AssignOperation#getArithmeticOperation <em>Arithmetic Operation</em>}</li>
 *   <li>{@link fr.ensma.gimpleDsl.AssignOperation#getBinaryOperation <em>Binary Operation</em>}</li>
 * </ul>
 *
 * @see fr.ensma.gimpleDsl.GimpleDslPackage#getAssignOperation()
 * @model
 * @generated
 */
public interface AssignOperation extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(EObject)
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getAssignOperation_Name()
   * @model containment="true"
   * @generated
   */
  EObject getName();

  /**
   * Sets the value of the '{@link fr.ensma.gimpleDsl.AssignOperation#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(EObject value);

  /**
   * Returns the value of the '<em><b>Cast</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cast</em>' attribute.
   * @see #setCast(boolean)
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getAssignOperation_Cast()
   * @model
   * @generated
   */
  boolean isCast();

  /**
   * Sets the value of the '{@link fr.ensma.gimpleDsl.AssignOperation#isCast <em>Cast</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cast</em>' attribute.
   * @see #isCast()
   * @generated
   */
  void setCast(boolean value);

  /**
   * Returns the value of the '<em><b>Vcall</b></em>' containment reference list.
   * The list contents are of type {@link fr.ensma.gimpleDsl.VariableCall}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vcall</em>' containment reference list.
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getAssignOperation_Vcall()
   * @model containment="true"
   * @generated
   */
  EList<VariableCall> getVcall();

  /**
   * Returns the value of the '<em><b>Temp Variable</b></em>' containment reference list.
   * The list contents are of type {@link fr.ensma.gimpleDsl.TempVariable}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Temp Variable</em>' containment reference list.
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getAssignOperation_TempVariable()
   * @model containment="true"
   * @generated
   */
  EList<TempVariable> getTempVariable();

  /**
   * Returns the value of the '<em><b>Function Call</b></em>' containment reference list.
   * The list contents are of type {@link fr.ensma.gimpleDsl.FunctionCall}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Call</em>' containment reference list.
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getAssignOperation_FunctionCall()
   * @model containment="true"
   * @generated
   */
  EList<FunctionCall> getFunctionCall();

  /**
   * Returns the value of the '<em><b>Arithmetic Operation</b></em>' containment reference list.
   * The list contents are of type {@link fr.ensma.gimpleDsl.ArithmeticOperation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arithmetic Operation</em>' containment reference list.
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getAssignOperation_ArithmeticOperation()
   * @model containment="true"
   * @generated
   */
  EList<ArithmeticOperation> getArithmeticOperation();

  /**
   * Returns the value of the '<em><b>Binary Operation</b></em>' containment reference list.
   * The list contents are of type {@link fr.ensma.gimpleDsl.BinaryOperation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Binary Operation</em>' containment reference list.
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getAssignOperation_BinaryOperation()
   * @model containment="true"
   * @generated
   */
  EList<BinaryOperation> getBinaryOperation();

} // AssignOperation
