/**
 * generated by Xtext 2.25.0
 */
package fr.ensma.gimpleDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boulean Exrpession</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ensma.gimpleDsl.BouleanExrpession#getInstruction <em>Instruction</em>}</li>
 *   <li>{@link fr.ensma.gimpleDsl.BouleanExrpession#getCodeBlock <em>Code Block</em>}</li>
 * </ul>
 *
 * @see fr.ensma.gimpleDsl.GimpleDslPackage#getBouleanExrpession()
 * @model
 * @generated
 */
public interface BouleanExrpession extends If
{
  /**
   * Returns the value of the '<em><b>Instruction</b></em>' containment reference list.
   * The list contents are of type {@link fr.ensma.gimpleDsl.Instruction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instruction</em>' containment reference list.
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getBouleanExrpession_Instruction()
   * @model containment="true"
   * @generated
   */
  EList<Instruction> getInstruction();

  /**
   * Returns the value of the '<em><b>Code Block</b></em>' containment reference list.
   * The list contents are of type {@link fr.ensma.gimpleDsl.CodeBlock}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code Block</em>' containment reference list.
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getBouleanExrpession_CodeBlock()
   * @model containment="true"
   * @generated
   */
  EList<CodeBlock> getCodeBlock();

} // BouleanExrpession
