/**
 * generated by Xtext 2.25.0
 */
package fr.ensma.gimpleDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cast</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.ensma.gimpleDsl.GimpleDslPackage#getCast()
 * @model
 * @generated
 */
public interface Cast extends EObject
{
} // Cast
