/**
 * generated by Xtext 2.25.0
 */
package fr.ensma.gimpleDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ensma.gimpleDsl.FunctionDef#getName <em>Name</em>}</li>
 *   <li>{@link fr.ensma.gimpleDsl.FunctionDef#getFunctionparam <em>Functionparam</em>}</li>
 *   <li>{@link fr.ensma.gimpleDsl.FunctionDef#getCodeBlock <em>Code Block</em>}</li>
 * </ul>
 *
 * @see fr.ensma.gimpleDsl.GimpleDslPackage#getFunctionDef()
 * @model
 * @generated
 */
public interface FunctionDef extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(Function)
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getFunctionDef_Name()
   * @model containment="true"
   * @generated
   */
  Function getName();

  /**
   * Sets the value of the '{@link fr.ensma.gimpleDsl.FunctionDef#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(Function value);

  /**
   * Returns the value of the '<em><b>Functionparam</b></em>' containment reference list.
   * The list contents are of type {@link fr.ensma.gimpleDsl.FunctionParam}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Functionparam</em>' containment reference list.
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getFunctionDef_Functionparam()
   * @model containment="true"
   * @generated
   */
  EList<FunctionParam> getFunctionparam();

  /**
   * Returns the value of the '<em><b>Code Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code Block</em>' containment reference.
   * @see #setCodeBlock(CodeBlock)
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getFunctionDef_CodeBlock()
   * @model containment="true"
   * @generated
   */
  CodeBlock getCodeBlock();

  /**
   * Sets the value of the '{@link fr.ensma.gimpleDsl.FunctionDef#getCodeBlock <em>Code Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Code Block</em>' containment reference.
   * @see #getCodeBlock()
   * @generated
   */
  void setCodeBlock(CodeBlock value);

} // FunctionDef
