/**
 * generated by Xtext 2.25.0
 */
package fr.ensma.gimpleDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ensma.gimpleDsl.FunctionCall#getCalledFunction <em>Called Function</em>}</li>
 *   <li>{@link fr.ensma.gimpleDsl.FunctionCall#getFunctionArgument <em>Function Argument</em>}</li>
 * </ul>
 *
 * @see fr.ensma.gimpleDsl.GimpleDslPackage#getFunctionCall()
 * @model
 * @generated
 */
public interface FunctionCall extends EObject
{
  /**
   * Returns the value of the '<em><b>Called Function</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Called Function</em>' reference.
   * @see #setCalledFunction(Function)
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getFunctionCall_CalledFunction()
   * @model
   * @generated
   */
  Function getCalledFunction();

  /**
   * Sets the value of the '{@link fr.ensma.gimpleDsl.FunctionCall#getCalledFunction <em>Called Function</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Called Function</em>' reference.
   * @see #getCalledFunction()
   * @generated
   */
  void setCalledFunction(Function value);

  /**
   * Returns the value of the '<em><b>Function Argument</b></em>' containment reference list.
   * The list contents are of type {@link fr.ensma.gimpleDsl.FunctionArgument}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Argument</em>' containment reference list.
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getFunctionCall_FunctionArgument()
   * @model containment="true"
   * @generated
   */
  EList<FunctionArgument> getFunctionArgument();

} // FunctionCall
