/**
 * generated by Xtext 2.25.0
 */
package fr.ensma.gimpleDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Goto</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ensma.gimpleDsl.Goto#getGoto <em>Goto</em>}</li>
 * </ul>
 *
 * @see fr.ensma.gimpleDsl.GimpleDslPackage#getGoto()
 * @model
 * @generated
 */
public interface Goto extends EObject
{
  /**
   * Returns the value of the '<em><b>Goto</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Goto</em>' reference.
   * @see #setGoto(Label)
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getGoto_Goto()
   * @model
   * @generated
   */
  Label getGoto();

  /**
   * Sets the value of the '{@link fr.ensma.gimpleDsl.Goto#getGoto <em>Goto</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Goto</em>' reference.
   * @see #getGoto()
   * @generated
   */
  void setGoto(Label value);

} // Goto
