/**
 * generated by Xtext 2.25.0
 */
package fr.ensma.gimpleDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logical Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.ensma.gimpleDsl.GimpleDslPackage#getLogicalOperation()
 * @model
 * @generated
 */
public interface LogicalOperation extends BouleanExrpession
{
} // LogicalOperation
