/**
 * generated by Xtext 2.25.0
 */
package fr.ensma.gimpleDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Struct</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ensma.gimpleDsl.Struct#getName <em>Name</em>}</li>
 *   <li>{@link fr.ensma.gimpleDsl.Struct#getAnother <em>Another</em>}</li>
 * </ul>
 *
 * @see fr.ensma.gimpleDsl.GimpleDslPackage#getStruct()
 * @model
 * @generated
 */
public interface Struct extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getStruct_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.ensma.gimpleDsl.Struct#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Another</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Another</em>' attribute.
   * @see #setAnother(String)
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getStruct_Another()
   * @model
   * @generated
   */
  String getAnother();

  /**
   * Sets the value of the '{@link fr.ensma.gimpleDsl.Struct#getAnother <em>Another</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Another</em>' attribute.
   * @see #getAnother()
   * @generated
   */
  void setAnother(String value);

} // Struct
