/**
 * generated by Xtext 2.25.0
 */
package fr.ensma.gimpleDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Switch Statment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ensma.gimpleDsl.SwitchStatment#getTempVariableRef <em>Temp Variable Ref</em>}</li>
 *   <li>{@link fr.ensma.gimpleDsl.SwitchStatment#getSwitchDefaultCase <em>Switch Default Case</em>}</li>
 *   <li>{@link fr.ensma.gimpleDsl.SwitchStatment#getSwitchCase1 <em>Switch Case1</em>}</li>
 * </ul>
 *
 * @see fr.ensma.gimpleDsl.GimpleDslPackage#getSwitchStatment()
 * @model
 * @generated
 */
public interface SwitchStatment extends EObject
{
  /**
   * Returns the value of the '<em><b>Temp Variable Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Temp Variable Ref</em>' reference.
   * @see #setTempVariableRef(TempVariable)
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getSwitchStatment_TempVariableRef()
   * @model
   * @generated
   */
  TempVariable getTempVariableRef();

  /**
   * Sets the value of the '{@link fr.ensma.gimpleDsl.SwitchStatment#getTempVariableRef <em>Temp Variable Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Temp Variable Ref</em>' reference.
   * @see #getTempVariableRef()
   * @generated
   */
  void setTempVariableRef(TempVariable value);

  /**
   * Returns the value of the '<em><b>Switch Default Case</b></em>' containment reference list.
   * The list contents are of type {@link fr.ensma.gimpleDsl.SwitchDefaultCase}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Switch Default Case</em>' containment reference list.
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getSwitchStatment_SwitchDefaultCase()
   * @model containment="true"
   * @generated
   */
  EList<SwitchDefaultCase> getSwitchDefaultCase();

  /**
   * Returns the value of the '<em><b>Switch Case1</b></em>' containment reference list.
   * The list contents are of type {@link fr.ensma.gimpleDsl.SwitchCase}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Switch Case1</em>' containment reference list.
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getSwitchStatment_SwitchCase1()
   * @model containment="true"
   * @generated
   */
  EList<SwitchCase> getSwitchCase1();

} // SwitchStatment
