/**
 * generated by Xtext 2.25.0
 */
package fr.ensma.gimpleDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Switch Default Case</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ensma.gimpleDsl.SwitchDefaultCase#getName <em>Name</em>}</li>
 *   <li>{@link fr.ensma.gimpleDsl.SwitchDefaultCase#getSwitchLabel <em>Switch Label</em>}</li>
 * </ul>
 *
 * @see fr.ensma.gimpleDsl.GimpleDslPackage#getSwitchDefaultCase()
 * @model
 * @generated
 */
public interface SwitchDefaultCase extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getSwitchDefaultCase_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.ensma.gimpleDsl.SwitchDefaultCase#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Switch Label</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Switch Label</em>' reference.
   * @see #setSwitchLabel(SwitchLabel)
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getSwitchDefaultCase_SwitchLabel()
   * @model
   * @generated
   */
  SwitchLabel getSwitchLabel();

  /**
   * Sets the value of the '{@link fr.ensma.gimpleDsl.SwitchDefaultCase#getSwitchLabel <em>Switch Label</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Switch Label</em>' reference.
   * @see #getSwitchLabel()
   * @generated
   */
  void setSwitchLabel(SwitchLabel value);

} // SwitchDefaultCase
