/**
 * generated by Xtext 2.25.0
 */
package fr.ensma.gimpleDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ensma.gimpleDsl.VariableCall#getCalledVaraible <em>Called Varaible</em>}</li>
 * </ul>
 *
 * @see fr.ensma.gimpleDsl.GimpleDslPackage#getVariableCall()
 * @model
 * @generated
 */
public interface VariableCall extends EObject
{
  /**
   * Returns the value of the '<em><b>Called Varaible</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Called Varaible</em>' reference.
   * @see #setCalledVaraible(LocalVariable)
   * @see fr.ensma.gimpleDsl.GimpleDslPackage#getVariableCall_CalledVaraible()
   * @model
   * @generated
   */
  LocalVariable getCalledVaraible();

  /**
   * Sets the value of the '{@link fr.ensma.gimpleDsl.VariableCall#getCalledVaraible <em>Called Varaible</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Called Varaible</em>' reference.
   * @see #getCalledVaraible()
   * @generated
   */
  void setCalledVaraible(LocalVariable value);

} // VariableCall
