/*
 * generated by Xtext 2.25.0
 */
package fr.ensma.ui.tests;

import com.google.inject.Injector;
import fr.ensma.gimple.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class GimpleDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("fr.ensma.GimpleDsl");
	}

}
