/**
 * generated by Xtext 2.25.0
 */
package fr.ensma.gimpleDsl.impl;

import fr.ensma.gimpleDsl.Function;
import fr.ensma.gimpleDsl.FunctionArgument;
import fr.ensma.gimpleDsl.FunctionCall;
import fr.ensma.gimpleDsl.GimpleDslPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Function Call</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.ensma.gimpleDsl.impl.FunctionCallImpl#getCalledFunction <em>Called Function</em>}</li>
 *   <li>{@link fr.ensma.gimpleDsl.impl.FunctionCallImpl#getFunctionArgument <em>Function Argument</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FunctionCallImpl extends MinimalEObjectImpl.Container implements FunctionCall
{
  /**
   * The cached value of the '{@link #getCalledFunction() <em>Called Function</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCalledFunction()
   * @generated
   * @ordered
   */
  protected Function calledFunction;

  /**
   * The cached value of the '{@link #getFunctionArgument() <em>Function Argument</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFunctionArgument()
   * @generated
   * @ordered
   */
  protected EList<FunctionArgument> functionArgument;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FunctionCallImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GimpleDslPackage.Literals.FUNCTION_CALL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Function getCalledFunction()
  {
    if (calledFunction != null && calledFunction.eIsProxy())
    {
      InternalEObject oldCalledFunction = (InternalEObject)calledFunction;
      calledFunction = (Function)eResolveProxy(oldCalledFunction);
      if (calledFunction != oldCalledFunction)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, GimpleDslPackage.FUNCTION_CALL__CALLED_FUNCTION, oldCalledFunction, calledFunction));
      }
    }
    return calledFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Function basicGetCalledFunction()
  {
    return calledFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCalledFunction(Function newCalledFunction)
  {
    Function oldCalledFunction = calledFunction;
    calledFunction = newCalledFunction;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GimpleDslPackage.FUNCTION_CALL__CALLED_FUNCTION, oldCalledFunction, calledFunction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<FunctionArgument> getFunctionArgument()
  {
    if (functionArgument == null)
    {
      functionArgument = new EObjectContainmentEList<FunctionArgument>(FunctionArgument.class, this, GimpleDslPackage.FUNCTION_CALL__FUNCTION_ARGUMENT);
    }
    return functionArgument;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GimpleDslPackage.FUNCTION_CALL__FUNCTION_ARGUMENT:
        return ((InternalEList<?>)getFunctionArgument()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GimpleDslPackage.FUNCTION_CALL__CALLED_FUNCTION:
        if (resolve) return getCalledFunction();
        return basicGetCalledFunction();
      case GimpleDslPackage.FUNCTION_CALL__FUNCTION_ARGUMENT:
        return getFunctionArgument();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GimpleDslPackage.FUNCTION_CALL__CALLED_FUNCTION:
        setCalledFunction((Function)newValue);
        return;
      case GimpleDslPackage.FUNCTION_CALL__FUNCTION_ARGUMENT:
        getFunctionArgument().clear();
        getFunctionArgument().addAll((Collection<? extends FunctionArgument>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GimpleDslPackage.FUNCTION_CALL__CALLED_FUNCTION:
        setCalledFunction((Function)null);
        return;
      case GimpleDslPackage.FUNCTION_CALL__FUNCTION_ARGUMENT:
        getFunctionArgument().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GimpleDslPackage.FUNCTION_CALL__CALLED_FUNCTION:
        return calledFunction != null;
      case GimpleDslPackage.FUNCTION_CALL__FUNCTION_ARGUMENT:
        return functionArgument != null && !functionArgument.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //FunctionCallImpl
