/**
 * generated by Xtext 2.25.0
 */
package fr.ensma.gimpleDsl.impl;

import fr.ensma.gimpleDsl.GimpleDslPackage;
import fr.ensma.gimpleDsl.LogicalOperation;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Logical Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LogicalOperationImpl extends BouleanExrpessionImpl implements LogicalOperation
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LogicalOperationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GimpleDslPackage.Literals.LOGICAL_OPERATION;
  }

} //LogicalOperationImpl
