/**
 * generated by Xtext 2.25.0
 */
package fr.ensma.gimpleDsl.impl;

import fr.ensma.gimpleDsl.GimpleDslPackage;
import fr.ensma.gimpleDsl.Struct;
import fr.ensma.gimpleDsl.StructVariableCall;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Struct Variable Call</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.ensma.gimpleDsl.impl.StructVariableCallImpl#getCalledStructVariable <em>Called Struct Variable</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StructVariableCallImpl extends MinimalEObjectImpl.Container implements StructVariableCall
{
  /**
   * The cached value of the '{@link #getCalledStructVariable() <em>Called Struct Variable</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCalledStructVariable()
   * @generated
   * @ordered
   */
  protected Struct calledStructVariable;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StructVariableCallImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GimpleDslPackage.Literals.STRUCT_VARIABLE_CALL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Struct getCalledStructVariable()
  {
    if (calledStructVariable != null && calledStructVariable.eIsProxy())
    {
      InternalEObject oldCalledStructVariable = (InternalEObject)calledStructVariable;
      calledStructVariable = (Struct)eResolveProxy(oldCalledStructVariable);
      if (calledStructVariable != oldCalledStructVariable)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, GimpleDslPackage.STRUCT_VARIABLE_CALL__CALLED_STRUCT_VARIABLE, oldCalledStructVariable, calledStructVariable));
      }
    }
    return calledStructVariable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Struct basicGetCalledStructVariable()
  {
    return calledStructVariable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCalledStructVariable(Struct newCalledStructVariable)
  {
    Struct oldCalledStructVariable = calledStructVariable;
    calledStructVariable = newCalledStructVariable;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GimpleDslPackage.STRUCT_VARIABLE_CALL__CALLED_STRUCT_VARIABLE, oldCalledStructVariable, calledStructVariable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GimpleDslPackage.STRUCT_VARIABLE_CALL__CALLED_STRUCT_VARIABLE:
        if (resolve) return getCalledStructVariable();
        return basicGetCalledStructVariable();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GimpleDslPackage.STRUCT_VARIABLE_CALL__CALLED_STRUCT_VARIABLE:
        setCalledStructVariable((Struct)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GimpleDslPackage.STRUCT_VARIABLE_CALL__CALLED_STRUCT_VARIABLE:
        setCalledStructVariable((Struct)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GimpleDslPackage.STRUCT_VARIABLE_CALL__CALLED_STRUCT_VARIABLE:
        return calledStructVariable != null;
    }
    return super.eIsSet(featureID);
  }

} //StructVariableCallImpl
