/*
 * generated by Xtext 2.25.0
 */
package fr.ensma.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGimpleDslScopeProvider extends DelegatingScopeProvider {
}
