/*
 * generated by Xtext 2.25.0
 */
package fr.ensma.parser.antlr;

import com.google.inject.Inject;
import fr.ensma.parser.antlr.internal.InternalGimpleDslParser;
import fr.ensma.services.GimpleDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GimpleDslParser extends AbstractAntlrParser {

	@Inject
	private GimpleDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGimpleDslParser createParser(XtextTokenStream stream) {
		return new InternalGimpleDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "TAC";
	}

	public GimpleDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GimpleDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
