/*
 * generated by Xtext 2.25.0
 */
package fr.ensma.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GimpleDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/ensma/parser/antlr/internal/InternalGimpleDsl.tokens");
	}
}
